### ISSUE TITLE
Incorrect dates starting with Season 1 Episode 12

### ISSUE THREAD

**Issue by ZetaRift** [JimAllanson/api.ponycountdown.com#3]
Should point out that S1 E12 aired on 2011-01-07.
You may want to look into the episodes' air dates a little more.

**Comment by JimAllanson** [comment]
Whoops, that's now fixed in f7e55d2cad8a32218ac7318dc609c46873329262, thanks for pointing it out. The other dates should hopefully all be correct, as they were added individually in advance of each episode airing, whereas season 1 was added in after the fact.
