### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by jaredallard** [JimAllanson/api.ponycountdown.com#5]
As per [npm guidelines](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git) you shouldn't track the node_modules folder in source

Awesome project :)

**Comment by JimAllanson** [comment]
Thanks, I've been meaning to remove the node_modules folder and the IntelliJ files for a while, I'll try to do it this evening if I remember.

**Comment by jaredallard** [comment]
I could PR it, if you want.

**Comment by JimAllanson** [comment]
Sorry, I forgot about this issue for a while. I've just done an update and removed the node_modules folder and IDE files.

**Comment by jaredallard** [comment]
Awesome! :)
